export const produtos = [
    {
        "id": 1,
        "nome": "Bolsa Solare",
        "categoria": "Acessório",
        "pasta": "bolsa-amarela-tassel",
        "preco": 150.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Bolsa em malha com alça e forrada. L: 25cm  A: 19cm"
    },
    {
        "id": 2,
        "nome": "Blusa Candy",
        "categoria": "Vestuário",
        "pasta": "blusa-colorida-soft",
        "preco": 299.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Blusa em crochê une conforto e estilo para compor looks leves e elegantes.  Tamanho M"
    },
    {
        "id": 3,
        "nome": "Bolsa Aurora Pink",
        "categoria": "Acessório",
        "pasta": "bolsa-grande-pink",
        "preco": 219.0,
        "estoque": 1,
        "prazo": 35,
        "destaque": "NÃO",
        "descricao": "Bolsa em fio algodao  forrada. L: 35cm  A: 35cm, com a alça A: 56cm"
    },
    {
        "id": 4,
        "nome": "Bolsa Esmeralda",
        "categoria": "Acessório",
        "pasta": "bolsa-verde-malha",
        "preco": 260.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Bolsa em malha com alça em couro e forrada. L: 24cm  A: 23cm"
    },
    {
        "id": 5,
        "nome": "Bolsa Évora",
        "categoria": "Acessório",
        "pasta": "bolsa-tricolor-verde-branco-bege-malha",
        "preco": 200.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Bolsa em malha tres cores e forrada. L: 28cm  A: 23cm"
    },
    {
        "id": 6,
        "nome": "Bolsa Trama Elegance",
        "categoria": "Acessório",
        "pasta": "bolsa-verde-limao-malha",
        "preco": 260.0,
        "estoque": 1,
        "prazo": 35,
        "destaque": "NÃO",
        "descricao": "Bolsa em malha com alça em couro e forrada. L: 25cm  A: 21cm"
    },
    {
        "id": 7,
        "nome": "Boneca Buque Flor",
        "categoria": "Bonecas",
        "pasta": "boneca-buque-flor",
        "preco": 210.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 23cm."
    },
    {
        "id": 8,
        "nome": "Boneca Coelho",
        "categoria": "Bonecas",
        "pasta": "boneca-coelho",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 30cm."
    },
    {
        "id": 9,
        "nome": "Boneca Inverno",
        "categoria": "Bonecas",
        "pasta": "boneca-inverno",
        "preco": 130.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalêrgenico.Acessórios remomíveis: touca, luvas e cachecol."
    },
    {
        "id": 10,
        "nome": "Brinquedo Pedagógico",
        "categoria": "Brinquedo",
        "pasta": "brinquedo-pedagogico-formas-geometricas",
        "preco": 100.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Ideal para crianças em fase de alfabetização, professores, terapeutas e famílias. 27 x 35cm"
    },
    {
        "id": 11,
        "nome": "Cavalo marinho",
        "categoria": "Brinquedo",
        "pasta": "cavalo-marinho",
        "preco": 90.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 28cm."
    },
    {
        "id": 12,
        "nome": "Centopeia Azul",
        "categoria": "Brinquedo",
        "pasta": "centopeia-azul",
        "preco": 110.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 30cm."
    },
    {
        "id": 13,
        "nome": "Chaveiro Borboleta",
        "categoria": "Chaveiros",
        "pasta": "chaveiro-borboleta",
        "preco": 8.0,
        "estoque": 4,
        "prazo": 5,
        "destaque": "NÃO",
        "descricao": "Perfeito para dar um toque de personalidade às suas chaves, bolsas, mochilas ou presentear clientes ou alguém que você gosta."
    },
    {
        "id": 14,
        "nome": "Chaveiro Coração",
        "categoria": "Chaveiros",
        "pasta": "chaveiro-coracao",
        "preco": 8.0,
        "estoque": 6,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Perfeito para dar um toque de personalidade às suas chaves, bolsas, mochilas ou presentear clientes ou alguém que você gosta."
    },
    {
        "id": 15,
        "nome": "Chaveiro Gatinho",
        "categoria": "Chaveiros",
        "pasta": "chaveiro-gatinho",
        "preco": 8.0,
        "estoque": 6,
        "prazo": 5,
        "destaque": "NÃO",
        "descricao": "Perfeito para dar um toque de personalidade às suas chaves, bolsas, mochilas ou presentear clientes ou alguém que você gosta."
    },
    {
        "id": 16,
        "nome": "Chaveiro Ursinho",
        "categoria": "Chaveiros",
        "pasta": "chaveiro-ursinho",
        "preco": 10.0,
        "estoque": 1,
        "prazo": 5,
        "destaque": "NÃO",
        "descricao": "Perfeito para dar um toque de personalidade às suas chaves, bolsas, mochilas ou presentear clientes ou alguém que você gosta."
    },
    {
        "id": 17,
        "nome": "Coeho Pequeno Articulado",
        "categoria": "Brinquedo",
        "pasta": "coelho-pequeno-articulado",
        "preco": 75.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 13cm."
    },
    {
        "id": 18,
        "nome": "Coelhinho Interativo",
        "categoria": "Brinquedo",
        "pasta": "coelhinho-interativo-chocalho-apito",
        "preco": 80.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 20cm."
    },
    {
        "id": 19,
        "nome": "Coelho Azul Branco",
        "categoria": "Brinquedo",
        "pasta": "coelho-azul-branco",
        "preco": 95.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 30cm."
    },
    {
        "id": 20,
        "nome": "Coelho Dentro da Cesta",
        "categoria": "Decoração",
        "pasta": "coelho-dentro-da-cesta",
        "preco": 80.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 20cm."
    },
    {
        "id": 21,
        "nome": "Coelho Grande Limãozinho",
        "categoria": "Brinquedo",
        "pasta": "coelho-grande-limaozinho",
        "preco": 300.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 40cm."
    },
    {
        "id": 22,
        "nome": "Coelho Grande Uvinha",
        "categoria": "Brinquedo",
        "pasta": "coelho-grande-uvinha",
        "preco": 300.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalergênico. Altura 40cm."
    },
    {
        "id": 23,
        "nome": "Coelho Porta Ovo",
        "categoria": "Brinquedo",
        "pasta": "coelho-porta-ovo",
        "preco": 70.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao  e enchimento hipoalergênico. Altura 20cm."
    },
    {
        "id": 24,
        "nome": "Flâmula coelho",
        "categoria": "Decoração",
        "pasta": "flamula-coelho",
        "preco": 100.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100%algodao.  Altura 40cm, largura 38(entre orelhas)."
    },
    {
        "id": 25,
        "nome": "Kit Bebe Ursinho com Naninha",
        "categoria": "Brinquedo",
        "pasta": "kit-bebe-ursinho-com-naninha",
        "preco": 250.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodão, enchimento hipoalergênico. O kit: ursinho, naninha, pegador e cordão para cortina."
    },
    {
        "id": 26,
        "nome": "kit cesta e pote com tampa",
        "categoria": "Decoração",
        "pasta": "kit-cesta-e-pote-com-tampa",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Confeccionado em malha, fundo mdf com cesto e pote com tampa."
    },
    {
        "id": 27,
        "nome": "Kit Cesto Organizador",
        "categoria": "Organização",
        "pasta": "kit-tres-cestos-fundo-MDF",
        "preco": 210.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Confeccionado em malha com tres potes diferentes tamanhos fundo mdf."
    },
    {
        "id": 28,
        "nome": "Kit Escritório Preto Malha",
        "categoria": "Organização",
        "pasta": "kit-escritorio-preto-malha",
        "preco": 100.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Confeccionado em malha com porta celular, tablet e lápis."
    },
    {
        "id": 29,
        "nome": "kit Jogo Americano Azul Brilho",
        "categoria": "Decoração",
        "pasta": "jogo-americano-azul-brilho-porta-copos",
        "preco": 200.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Jogo americano em malha brilho contendo 4 sousplat e 4 porta copos. 35cm"
    },
    {
        "id": 30,
        "nome": "kit Jogo Americano Bicolor Azul claro e escuro",
        "categoria": "Decoração",
        "pasta": "jogo-americano-bicolor-azul-claro-escuro",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Jogo americano em malha  com 4 unidades. 34cm"
    },
    {
        "id": 31,
        "nome": "kit Jogo Americano Retangular Brilho",
        "categoria": "Decoração",
        "pasta": "jogo-americano-retangular-brilho",
        "preco": 180.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Jogo americano retangular em malha brilho com 3 unidades. 40 x 20cm"
    },
    {
        "id": 32,
        "nome": "Kit Organizador cesto e potes com tampa",
        "categoria": "Organização",
        "pasta": "kit-organizador-cesto-e-potes-com-tampa",
        "preco": 200.0,
        "estoque": 1,
        "prazo": 35,
        "destaque": "NÃO",
        "descricao": "Confeccionado em malha com dois potes com tampas."
    },
    {
        "id": 33,
        "nome": "Kit porta copos cores diferentes",
        "categoria": "Decoração",
        "pasta": "porta-copos-cores-diferentes",
        "preco": 45.0,
        "estoque": 1,
        "prazo": 8,
        "destaque": "NÃO",
        "descricao": "Confeccionados com fio 100% algodao com 6 unidades, cores variadas."
    },
    {
        "id": 34,
        "nome": "Kit Porta Copos Flor ocre",
        "categoria": "Decoração",
        "pasta": "porta-copos-flor-ocre",
        "preco": 30.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionados com fio 100% algodao com 4 unidades."
    },
    {
        "id": 35,
        "nome": "Kit Porta Copos Pedra Quente",
        "categoria": "Decoração",
        "pasta": "porta-copos-pedra-quente",
        "preco": 30.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionados com fio 100% algodao com 4 unidades."
    },
    {
        "id": 36,
        "nome": "Kit Porta Xícaras Brilho Colorido",
        "categoria": "Decoração",
        "pasta": "porta-xicara-brilho",
        "preco": 50.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionados com fio 100% algodao brilho com 5 unidades."
    },
    {
        "id": 37,
        "nome": "Kit Ursinho Aviador",
        "categoria": "Brinquedo",
        "pasta": "kit-ursinho-aviador-com-naninha",
        "preco": 310.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodão, enchimento hipoalergênico. O kit: ursinho, naninha, aviao."
    },
    {
        "id": 38,
        "nome": "Mochila Amor Prefeito",
        "categoria": "Acessório",
        "pasta": "mochila-rosa-malha",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Mochila infantil rosa em malha forrada com chaveierto coraçao.  A: 18cm L: 21cm P: 8cm."
    },
    {
        "id": 39,
        "nome": "Mochila Coelho",
        "categoria": "Mochilas",
        "pasta": "mochila-infantil-coelhinho",
        "preco": 210.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Mochila infantil 100% algodao com coelhinho. A: 30cm L: 20cm P: 10cm."
    },
    {
        "id": 40,
        "nome": "Naninha Ovelha",
        "categoria": "Brinquedo",
        "pasta": "naninha-ovelha",
        "preco": 50.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% e enchimento hipoalergênico. Altura 40cm."
    },
    {
        "id": 41,
        "nome": "Porta Celular Rosa Malha",
        "categoria": "Organização",
        "pasta": "porta-celular-rosa-malha",
        "preco": 50.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Confeccionado em malha para celular. A: 11,5cm   L:10cm    P: 8,5cm"
    },
    {
        "id": 42,
        "nome": "Porta Celular Verde Malha",
        "categoria": "Organização",
        "pasta": "porta-celular-verde-malha",
        "preco": 50.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Confeccionado em malha para celular. A: 11cm   L:12cm    P: 9,5cm"
    },
    {
        "id": 43,
        "nome": "Porta Maternidade Redondo Ovelha",
        "categoria": "Decoração",
        "pasta": "porta-maternidade-ovelhinha",
        "preco": 180.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Encante a chegada do seu bebê com um porta maternidade artesanal, feito à mão em amigurumi. Diametro:25cm"
    },
    {
        "id": 44,
        "nome": "Porta Maternidade Redondo Ursinho",
        "categoria": "Decoração",
        "pasta": "porta-maternidade-ursinho-redondo",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Encante a chegada do seu bebê com um porta maternidade artesanal, feito à mão em amigurumi. Diametro: 30cm"
    },
    {
        "id": 45,
        "nome": "Quadro Porta Maternidade Safari",
        "categoria": "Decoração",
        "pasta": "quadro-porta-maternidade-safari",
        "preco": 250.0,
        "estoque": 1,
        "prazo": 30,
        "destaque": "NÃO",
        "descricao": "Encante a chegada do seu bebê com um porta maternidade artesanal, feito à mão em amigurumi. 30 x 30"
    },
    {
        "id": 46,
        "nome": "Saida de Praia Ibiza",
        "categoria": "Vestuário",
        "pasta": "saida-praia-salmao",
        "preco": 200.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Ideal para dias de verão, praia, passeios a beira mar. Tam.: P"
    },
    {
        "id": 47,
        "nome": "Tapete da Contagem",
        "categoria": "Brinquedo",
        "pasta": "brinquedo-pedagogico-numerico",
        "preco": 100.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Ideal para crianças em fase de alfabetização, professores, terapeutas e famílias."
    },
    {
        "id": 48,
        "nome": "Tapete Hexagonal Verde",
        "categoria": "Decoração",
        "pasta": "tapete-hexagonal-verde",
        "preco": 100.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Com fio 100% algodao, macios, resistentes e fáceis de lavar, perfeitos para o dia a dia. 70 x 70cm"
    },
    {
        "id": 49,
        "nome": "Tapete Oval Bicolor",
        "categoria": "Decoração",
        "pasta": "tapete-oval-bicolor",
        "preco": 95.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Com fio 100% algodao, macios, resistentes e fáceis de lavar, perfeitos para o dia a dia. 66 x 47cm"
    },
    {
        "id": 50,
        "nome": "Tapete Redondo natural e cinza",
        "categoria": "Decoração",
        "pasta": "tapete-redondo-natural-cinza",
        "preco": 195.0,
        "estoque": 1,
        "prazo": 35,
        "destaque": "NÃO",
        "descricao": "Com fio 100% algodao, macios, resistentes e fáceis de lavar, perfeitos para o dia a dia. Diametro: 80cm"
    },
    {
        "id": 51,
        "nome": "Tapete Retangular Cinza",
        "categoria": "Decoração",
        "pasta": "tapete-retangular-cinza",
        "preco": 80.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Com fio 100% algodao, macios, resistentes e fáceis de lavar, perfeitos para o dia a dia. 70 x 38cm"
    },
    {
        "id": 52,
        "nome": "Tapete Xadrez Verde",
        "categoria": "Decoração",
        "pasta": "tapete-xadrez-verde",
        "preco": 80.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Com fio 100% algodao, macios, resistentes e fáceis de lavar, perfeitos para o dia a dia. 56 x 23cm"
    },
    {
        "id": 53,
        "nome": "Top Serena",
        "categoria": "Vestuário",
        "pasta": "top-azul",
        "preco": 140.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "top em crochê une conforto e estilo para compor looks leves e elegantes. Tamanho P"
    },
    {
        "id": 54,
        "nome": "Torre Donuts e Chantily",
        "categoria": "Brinquedo",
        "pasta": "brinquedo-encaixe-donuts",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Brinque com alegria e trabalhe a coordenação motora de forma divertida. A: 28cm"
    },
    {
        "id": 55,
        "nome": "Ursinha Troca Roupa",
        "categoria": "Bonecas",
        "pasta": "ursinha-troca-roupa",
        "preco": 190.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% algodao e enchimento hipoalêrgenico.Acessórios remomíveis: vestido, sapatos  macacao. A: 31cm"
    },
    {
        "id": 56,
        "nome": "Ursinho Sentado Marrom",
        "categoria": "Brinquedo",
        "pasta": "ursinho-sentado-marrom",
        "preco": 60.0,
        "estoque": 1,
        "prazo": 10,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% e enchimento hipoalergênico. Altura 13cm."
    },
    {
        "id": 57,
        "nome": "Macaco Interativo",
        "categoria": "Brinquedo",
        "pasta": "macaco-interativo",
        "preco": 90.0,
        "estoque": 1,
        "prazo": 20,
        "destaque": "NÃO",
        "descricao": "Confeccionado com fio 100% e enchimento hipoalergênico. Altura 28cm."
    },
    {
        "id": 58,
        "nome": "Sousplat Azul com Dourado",
        "categoria": "Decoração",
        "pasta": "sousplat-azul-dourado",
        "preco": 45.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 40cm"
    },
    {
        "id": 59,
        "nome": "Sousplat Marrom",
        "categoria": "Decoração",
        "pasta": "sousplat-marrom",
        "preco": 38.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 44cm"
    },
    {
        "id": 60,
        "nome": "Sousplat rosa",
        "categoria": "Decoração",
        "pasta": "sousplat-rosa",
        "preco": 41.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 34cm"
    },
    {
        "id": 61,
        "nome": "Kit Sousplat Encanto",
        "categoria": "Decoração",
        "pasta": "kit-sousplat-natural-encanto",
        "preco": 180.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 40cm, porta copo: 14cm diâm.,  porta guardanapo: 7cm diâm., caminho: 1050 X 37com."
    },
    {
        "id": 62,
        "nome": "Kit Sousplat Flor",
        "categoria": "Decoração",
        "pasta": "kit-sousplat-flor-marrom-natural",
        "preco": 70.0,
        "estoque": 1,
        "prazo": 25,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 36cm, porta copo: 16cm"
    },
    {
        "id": 63,
        "nome": "Sousplat Azul Marinho",
        "categoria": "Decoração",
        "pasta": "sousplat-azul-marinho",
        "preco": 35.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 38cm"
    },
    {
        "id": 64,
        "nome": "Sousplat verde",
        "categoria": "Decoração",
        "pasta": "sousplat-verde",
        "preco": 30.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 38cm"
    },
    {
        "id": 65,
        "nome": "Sousplat Caqui",
        "categoria": "Decoração",
        "pasta": "sousplat-bege-caqui",
        "preco": 35.0,
        "estoque": 1,
        "prazo": 15,
        "destaque": "NÃO",
        "descricao": "Uma peça que une beleza e personalidade á sua mesa. Diâmetro: 36cm"
    },
    {
        "id": 66,
        "nome": "Porta Copo ou Xícara",
        "categoria": "Decoração",
        "pasta": "porta-copo-xicara-flor",
        "preco": 18.0,
        "estoque": 1,
        "prazo": 8,
        "destaque": "NÃO",
        "descricao": "Porta copo ou xícara Diâmetro: 16cm"
    }
];